import 'package:equatable/equatable.dart';

/// generate by https://javiercbk.github.io/json_to_dart/
class AutogeneratedChat {
  final List<ChatModel> results;

  AutogeneratedChat({this.results});

  factory AutogeneratedChat.fromJson(Map<String, dynamic> json) {
    List<ChatModel> temp;
    if (json['results'] != null) {
      temp = List<ChatModel>();
      json['results'].forEach((v) {
        temp.add(ChatModel.fromJson(v));
      });
    }
    return AutogeneratedChat(results: temp);
  }
}

class ChatModel extends Equatable {
  final String id;
  final String date;
  final String receiver;
  final String sender;
  final String lastMessage;

  ChatModel(this.id, this.date, this.receiver, this.sender, this.lastMessage);

  @override
  List<Object> get props => [id, date, receiver, sender];

  factory ChatModel.fromJson(Map<String, dynamic> json) {
    return ChatModel(
      json['id'],
      json['date'],
      json['receiver'],
      json['sender'],
      json['lastMessage'],
    );
  }
}
